### PR TITLE
InstallReferrer only for Play

### PR DESCRIPTION
**Pull request by licaon-kter**
...right?

But you might need to make some placefolder files elsewhere too, eg: https://github.com/iNPUTmice/Conversations/blob/master/src/conversationsFree/java/eu/siacs/conversations/utils/InstallReferrerUtils.java

### CODE REVIEW

**Comment by ge0rg** [comment]
Yes, `src/org/yaxim/androidclient/service/InstallReferrerReceiver.java` needs to be moved to `play/...` and a dummy class similar to `PushManager` needs to be created under `free/...`. Feel free to do so :)

**Comment by ge0rg** [comment]
BTW, do you know if F-Droid also has something comparable to an Install Referrer? It'd be a good thing, probably, to have a nice integrated single-click installation via https://join.jabber.network/#demo.user@domain

**Comment by ge0rg** [comment]
Merged in 55d0ce6a3cc645b68db104bc43c50a7233912d0d.

Also implemented the above-mentioned changes in 4a8ef839c6220109aeb74920e2afe8f84c23635a.

**Comment by licaon-kter** [comment]
F-Droid has no such thing yet: https://gitlab.com/fdroid/fdroidclient/-/issues/1932

**Pull request closed without merging**
